baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "KumaWeb"
languageCode = "ja"
theme = "hugo-material-docs"

[params]
# General information
author = "Shota Takahashi"
description = "Welcome to Kuma's Webpage"
copyright = "Released under the MIT license"

# Repository
provide = "GitHub"
repo_url = "https://github.com/shotakaha/kumaweb"
version = "1.0.0"
logo = "images/logo.png"
favicon = ""

permalink = "#"

# Custom assets
custom_css = []
custom_js  =  []

# Syntax highlighting theme
highlight_css = ""

[params.palette]
primary = "red"
accent  = "teal"

[params.font]
text = "Ubuntu"
code = "Ubuntu Mono"

[social]
twitter = ""
github  = ""
email   = ""


[[menu.main]]
name   = "Shota × Kuma"
url    = "/"
weight = 0

[[menu.main]]
name   = "Getting started"
url    = "getting-started/"
weight = 10

[[menu.main]]
name   = "Adding content"
url    = "adding-content/"
weight = 20

[[menu.main]]
name   = "Roadmap"
url    = "roadmap/"
weight = 30

[[menu.main]]
name   = "License"
url    = "license/"
weight = 40

[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true
